### ISSUE TITLE
Do not allow trailing whitespace

### ISSUE THREAD

**Issue by jfly** [thewca/wca-regulations-compiler#8]
This drives me crazy. I'll be happy to add the check if someone can point me in the right direction. Would adding a regex [here](https://github.com/jfly/wca-regulations-compiler/blob/8cbb7a82314d89610e14f7187f8b44f773e4ef8c/wrc/parse/parser.py#L39-L61) be an acceptable implementation?

**Comment by viroulep** [comment]
This is here because pandoc consider 4 whitespaces as a line break.

I tried to stick to how the Regulations were formatted, but I'm obviously in favor of not allowing trailing whitespaces :)

Quick details on how it works: the lexer transforms the input file in a sequence of tokens, and the parser check that the order of the tokens makes sense.
So right know each text in a paragraph is a `TEXT` token described [here](https://github.com/jfly/wca-regulations-compiler/blob/8cbb7a82314d89610e14f7187f8b44f773e4ef8c/wrc/parse/lexer.py#L100-L104). It defines a text as not starting by any of these character `<#\n `, having more than 0 characters, and ending with a `\n`.
So I think the correct way is to alter the regexp recognizing that token to prevent a whitespace character before the '\n', so that the compiler will throw a lexical error because a single whitespace token alone is not in the language.

Right now there is a specific codegen replacement for this weird convention [here](https://github.com/jfly/wca-regulations-compiler/blob/8cbb7a82314d89610e14f7187f8b44f773e4ef8c/wrc/codegen/cghtml.py#L79).

One particular thing to keep in mind is to check if the html rendering is still ok, as we may miss a `<br/>` on the two lines concerned.

If you're not in a hurry I can look at this on Thursday.

**Comment by jfly** [comment]
> If you're not in a hurry I can look at this on Thursday.

It's all you! I've assigned this issue to you =)
